# fly.toml app configuration file generated for docs-frontend on 2024-02-19T19:39:36-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'docs-frontend'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
