name: Tests

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  tests-karma:
    strategy:
      matrix:
        os-version: [ubuntu-latest]
        node-version: [18.x]
    runs-on: ${{ matrix.os-version }}

    steps:
    - name: Clone Repo
      uses: actions/checkout@v4.1.1

    - name: Prepare java
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install clojure cli
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: 1.11.1.1435

    - name: Karma Tests ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm ci
        npm run test

  tests-jsdom:
    strategy:
      matrix:
        os-version: [ubuntu-latest]
        node-version: [18.x]

    runs-on: ${{ matrix.os-version }}
    steps:
    - name: Clone Repo
      uses: actions/checkout@v4.1.1

    - name: Prepare java
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install clojure cli
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: 1.11.1.1435

    - name: JSDOM Tests ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm ci
        npm run test:node
