name: Tests

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  tests-karma:
    strategy:
      matrix:
        os-version: [ubuntu-latest]
        node-version: [18.x]
    runs-on: ${{ matrix.os-version }}

    steps:
    - name: Clone Repo
      uses: actions/checkout@v4.1.1

    - name: Prepare java
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install clojure cli
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: 1.11.2.1446

    - name: Karma Tests ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        npm ci
        npm run test

  tests-jsdom:
    strategy:
      matrix:
        os-version: [ubuntu-latest]
        node-version: [18.x]

    runs-on: ${{ matrix.os-version }}
    steps:
    - name: Clone Repo
      uses: actions/checkout@v4.1.1

    - name: Prepare java
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install clojure cli
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: 1.11.2.1446

    - name: JSDOM Tests ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        npm ci
        npm run test:node

  check-lint:
     strategy:
       matrix:
         operating-system: [ubuntu-latest]

     runs-on: ${{ matrix.operating-system }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4

       - name: Install clojure cli
         uses: DeLaGuardo/setup-clojure@master
         with:
           cli: 1.11.2.1446

       - name: Setup clojure-lsp
         uses: clojure-lsp/setup-clojure-lsp@v1.0.2
         with:
           clojure-lsp-version: 2024.03.13-13.11.00

       - name: Execute lint checks
         run: |
           clojure-lsp format --dry
           clojure-lsp clean-ns --dry
           clojure-lsp diagnostics
